### ISSUE TITLE
here is a bug when I use EDICT.ipynb

### ISSUE THREAD

**Issue by AshleyRm** [salesforce/EDICT#13]
Excellent work, I am trying to use EDICT.ipynb in jupyter notebook. I have not chage any code.
Can you please take a look and see if there are any problems?
Thank you so much!

![screenshot20231103](https://github.com/salesforce/EDICT/assets/95748505/80794a60-59f2-4c6f-8538-6cf71c14d198)

**Comment by AshleyRm** [comment]
I am a fresh man so....thank you

**Comment by AshleyRm** [comment]
I am sorry for bother
I will very appreciate if you can help me, it is meaning a lot.
Thank you

**Comment by ezgiekiz** [comment]
Installing transformers==4.19.2 solves the issue for me.

**Comment by AshleyRm** [comment]
> Installing transformers==4.19.2 solves the issue for me.

It is work!
Thank you so much

**Comment by bram-w** [comment]
Sorry for the delay here. I see you marked this as resolved but just wanted
to check in
