### ISSUE TITLE
Question about Figure 5 in the paper

### ISSUE THREAD

**Issue by yanzengatsmu** [salesforce/EDICT#14]
I guess the graph in Figure 5 represents the changing of cosine similarity between x_t and y_t. From left to right, the first part(50 to 0) is the generating process and the second part(0 to 50) is the inversion process. My question is, for the second graph, how did you get the initial latents of a real image at timestep 50 in the left side?

**Comment by bram-w** [comment]
Hello! Thanks for this question, it looks like this figure actually had a
typo in it: the x-ticks on the bottom should be 0-50-0 instead of 50-0-50.
Thanks for bringing this up!

**Comment by yanzengatsmu** [comment]
Thanks for your reply.
