### ISSUE TITLE
About COCO reconstruction MSE using LDM AE

### ISSUE THREAD

**Issue by zhihongp** [salesforce/EDICT#5]
As reported in Table 1, the MSE is 0.015.  But I get 0.022 using the same settings as yours based on understand: using stable diffusion v1.4, 5000 COCO val images and image normalized to (-1, 1).  Is there anything I am missing here?

**Comment by bram-w** [comment]
Hello, thanks for your interest! If you post your code I can check it out after the ICML deadline next week and post our reconstruction code/compare? You can also experiment with our codes recon error by use `EDICT_editing` with `init_image_strength=0` to just encode/decode with the VAE iirc.

**Comment by zhihongp** [comment]
Believe I have found the reason.  Instead of using central crop and resize to 512x512, I didn't crop and resized w,h so that %64=0

**Comment by zhihongp** [comment]
And you have to use NN for Image.resize(), otherwise it's MSE=0.018 instead of 0.015
