### ISSUE TITLE
Confused by comment in the code

### ISSUE THREAD

**Issue by andreaferretti** [salesforce/EDICT#6]
Hi, first thank you for the great work! I am trying to match the paper with the existing code, but I am confused by the [following comment](https://github.com/salesforce/EDICT/blob/b2e8eb1de9d16225279c92627eb805681da940da/edict_functions.py#L85-L91):

```
       run_baseline:
            VERY IMPORTANT
            True is EDICT, False is DDIM
    Output:
        PAIR of Images (tuple)
        If run_baseline=True then [0] will be edit and [1] will be original
        If run_baseline=False then they will be two nearly identical edited versions
```

If I understand correctly, to run EDICT, one should set `run_baseline=False` (this is consistent with the notebooks), and then the outputs will be two almost identical images, which is to be expected because of the coupling. This is in contrast with what the comment says, so I am trying to understand whether it's just a typo.

Moreover, it is not entirely clear to me why setting `run_baseline=True` should reproduce DDIM inversion. I mean, I guess it amounts to doing the appropriate changes in the code, but then what does it have to do with getting the reconstruction of the original image as the second element?

**Comment by bram-w** [comment]
Hi! Thanks for your interest and patience here.

The reason for the duplication is for the code's sake, nothing algorithmic. Basically it was easier to write everything else around this function if it always returns a tuple of images. 

What happens internally is that [0] gets operated on while [1] gets ignored, and so is returned unedited.
