### ISSUE TITLE
does it work on MacOS / ARM?

### ISSUE THREAD

**Issue by mbutterick** [salesforce/EDICT#8]
Thank you for this research. I'm not looking for detailed installation instructions, but just a more basic question: whether this code can be made to work on MacOS ARM at all, or if your `environment.yaml` presumes Windows/Linux.

**Comment by bram-w** [comment]
Thanks for your interest! Good question; haven't considered this. Given that we just did an environment dump for the yaml I could definitely see some of the stuff there being OS specific. You could probably make a more minimal one that would generalize better based off the top-level packages imported at https://github.com/salesforce/EDICT/blob/main/edict_functions.py#L1; let the installer sort out the versioning and just expand the yaml as needed.
